#include <iostream>
#include <string>
#include <cstdlib>
#include <cstdio>
#include <verilated.h> // Defines common routines
#include "VMIPS32SOC.h" // This file is generated by verilator

VMIPS32SOC *uut; // Instantiation of module

int main(int argc, char** argv)
{

	uut = new VMIPS32SOC;
  uut->clk = 0;
  uut->read_address1 = 0;
  uut->read_address2 = 1;
  uut->write_address = 3;
  uut->func = 1;
  uut->write_enable = 1;
  uut->eval();

  for(int i=0; i<50;i++){
    uut->clk = !(uut->clk);
    uut->eval();
  }

  for(int i=0; i<32;i++){
    printf("RegisterFile[%d] = %x\n",i,uut->MIPS32SOC__DOT__RegisterFile__DOT__registeries[i]);
  }

  printf("IsZero = %d\n", uut->isZero);

  uut->final();
	delete uut;

	return 0;

}
